### PR TITLE
Add image analysis tools to HEASARC

### PR DESCRIPTION
**Pull request by zoghbi-a**
This PR adds the image analysis tools: js9, jdaviz and ds9 (through vnc).

### CODE REVIEW

**Comment by zoghbi-a** [comment]
Just rebased to include the recent additions to the main branch to prepare for merging.

**Comment by esabol** [comment]
Hi, @zoghbi-a. Not sure if you saw, but XMM SAS 21.0.0 was released recently...

https://www.cosmos.esa.int/web/xmm-newton/sas-download

**Comment by zoghbi-a** [comment]
> Hi, @zoghbi-a. Not sure if you saw, but XMM SAS 21.0.0 was released recently...
> 
> https://www.cosmos.esa.int/web/xmm-newton/sas-download

Yes. I saw that. I plan to update it once heasoft 6.32 is out sometime in June. I am told there are bugs in the new SAS that will be need to be fixed.

**Comment by esabol** [comment]
Good to know. Thanks!

**Pull request merged**
